#!/bin/bash
set -e

if [[ -x $ZWA_INSTALL_DIR/bin/python ]]; then
  PYTHON=$ZWA_INSTALL_DIR/bin/python
else
  PYTHON=python
fi

export DEV_INSTALL_DIR=$ZWA_INSTALL_DIR

cmd=$1
shift
case "$cmd" in
	get_version)
		head -1 debian/changelog | sed -e 's/.*(\([^)]*\)).*/\1/'
		;;
	build-exclude-list|dist-exclude-list)
		## These lists can be used to delegate build-time and dist-time exclude lists
		## For example (syslog-ng-agent):
		##
		##    echo "out obj *.aqt *.ncb *.suo *.vcproj.*.user" 
		##
		;;
	prepare-dist)
		;;
	bootstrap)
		QUILT_PATCHES=debian/patches quilt push -a
		;;
	configure)
		echo "No need to configure"
		;;
	make)
		if [[ $# -gt 0 && "X$1" == Xinstall ]]; then
			PYTHON_VERSION_MAJOR=[`python -c "import sys; print '%d' % (sys.version_info[0]);"`]
			PYTHON_VERSION_MINOR=[`python -c "import sys; print '%d' % (sys.version_info[1]);"`]
			PYTHON_VERSION="${PYTHON_VERSION_MAJOR}.${PYTHON_VERSION_MINOR}"
			python setup.py install --prefix $ZWA_INSTALL_DIR
		elif [[ $# -gt 0 && "X$1" == Xclean ]]; then
			python setup.py clean
		else
			echo "Try make install instead of $1 $@"
		fi
		;;
	*)
		echo "Unknown command: $cmd" >&2
		exit 1
		;;
	esac
